### ISSUE TITLE
C++ Support

### ISSUE THREAD

**Issue by wiescho** [kyak/qnx_ert#1]
Hallo kyak,

after activating the C++ support in the qnxtool.mak changing the language to C++ in the configuration parameters and adding several rules in the template file so it will compile the  matlab autogenerated .cpp files  like in the tornado tmf:
`%.o : %.cpp`
`$(CC) $(CFLAGS) $<`

this error will accrue after the build process was started:

`C:/QNX650/host/win32/x86/usr/bin/qcc -lang-c++ -g  -V4.4.2,gcc_ntox86 -Bstatic -static             -DON_TARGET_WAIT_FOR_START=0 -DTID01EQ=1  -DEXT_MODE -DWIN32  - DVERBOSE -DQNX_OS -DMODEL=qnx_simple -DNUMST=3 -DNCSTATES=3 -DMAT_FILE=0 -DINTEGER_CODE=0 -DONESTEPFCN=1 -DTERMFCN=0 - DHAVESTDIO -DMULTI_INSTANCE_CODE=0 -DMT=1 -I. -I..  -I..   - IU:/IES/miesys/Matlab/ONX/qnx_ert-0.4/demos/qnx_simple_qnx_rtw -IU:/IES/miesys/Matlab/ONX/qnx_ert-0.4/demos -IC:/PROGRA~1/MATLAB/R2014a/toolbox/coder/rtiostream/src/utils  -IC:/PROGRA~1/MATLAB/R2014a/simulink/include -IC:/PROGRA~1/MATLAB/R2014a/extern/include -IC:/PROGRA~1/MATLAB/R2014a/rtw/c/src -IC:/PROGRA~1/MATLAB/R2014a/rtw/c/libsrc -IC:/PROGRA~1/MATLAB/R2014a/rtw/c/src/ext_mode/common -IC:/PROGRA~1/MATLAB/R2014a/rtw/c/src/ext_mode/tcpip -IC:/PROGRA~1/MATLAB/R2014a/rtw/c/src/ext_mode/serial -IC:/PROGRA~1/MATLAB/R2014a/rtw/c/src/ext_mode/custom -IC:/PROGRA~1/MATLAB/R2014a/toolbox/dspblks/src/sim -IC:/PROGRA~1/MATLAB/R2014a/toolbox/dspblks/src/rt -IC:/PROGRA~1/MATLAB/R2014a/toolbox/commblks/commmex -IC:/QNX650/target/qnx6/usr/include   -IU:\IES\miesys\Matlab\ONX\qnx_ert-0.4 -IU:\IES\miesys\Matlab\ONX\qnx_ert-0.4/ext_mode/target -IU:\IES\miesys\Matlab\ONX\qnx_ert-0.4/qnx  qnx_simple.cpp
C:/QNX650/target/qnx6/x86/lib/crt1.o:(.text+0x4): undefined reference to `main' 
C:/QNX650/target/qnx6/x86/lib/crt1.o: In function `_start': 
(.text+0x86): undefined reference to `main' 
C:\Users\WIESCH~1\AppData\Local\Temp\2qcc1zlPnb\qnx_simple.o: In function `qnx_simple_step0': 
U:\IES\miesys\Matlab\ONX\qnx_ert-0.4\demos\qnx_simple_qnx_rtw/qnx_simple.cpp:145: undefined reference to `qnx_simple_P' 
U:\IES\miesys\Matlab\ONX\qnx_ert-0.4\demos\qnx_simple_qnx_rtw/qnx_simple.cpp:151: undefined reference to `qnx_simple_P' 
U:\IES\miesys\Matlab\ONX\qnx_ert-0.4\demos\qnx_simple_qnx_rtw/qnx_simple.cpp:151: undefined reference to `qnx_simple_P' 
U:\IES\miesys\Matlab\ONX\qnx_ert-0.4\demos\qnx_simple_qnx_rtw/qnx_simple.cpp:152: undefined reference to `qnx_simple_P' 
U:\IES\miesys\Matlab\ONX\qnx_ert-0.4\demos\qnx_simple_qnx_rtw/qnx_simple.cpp:162: undefined reference to `qnx_simple_P' 
C:\Users\WIESCH~1\AppData\Local\Temp\2qcc1zlPnb\qnx_simple.o:U:\IES\miesys\Matlab\ONX\qnx_ert-0.4\demos\qnx_simple_qnx_rtw/qnx_simple.cpp:167: more undefined references to `qnx_simple_P' follow`

**Comment by kyak** [comment]
Ok, i will have to have a closer look. I only tried "C" code generation option with C++ compiler. 

Meanwhile, could you provide more information?
- MATLAB release
- What options did you set for  C++ code generation (encapsulation, class interfaces etc). Better yet, provide the model itself.
- Your QNX target (i guess it is x86, but anyway)
- Exact changes you made to the current target support package

**Comment by wiescho** [comment]
Hi,
I'm using Matlab 2014a with your qnx_simple model for testing purpose but my model with integrated c++ sfunctions generates a similar error. The only extra option I made is a change from c to c++ in the Target selection pane from Code Generation.
Your right it is a x86 target

As for changes in the target support package, I added 
           `256 CPPFLAGS = $(CFLAGS)`
and 

```
       %.o : %.cpp
             $(CC) $(CPPFLAGS) $<
       %.o : ../%.cpp
          $(CC) $(CPPFLAGS) $<
     |>START_EXPAND_RULES<|%.o : |>EXPAND_DIR_NAME<|/%.cpp
      $(CC) $(CPPFLAGS) $<
   |>END_EXPAND_RULES<|


   %.o : $(MATLAB_ROOT)/simulink/src/%.cpp
      $(CC) $(CPPFLAGS) $<
```

in the ert_qnx.tmf
Here's a link to the files:
https://www.dropbox.com/sh/y33dmaua62wkvk5/AADyj263mnVoiRuRWWH1zQuBa

**Comment by kyak** [comment]
Hi,

I've made some changes to support C++ code generation:
https://github.com/kyak/qnx_ert/commit/76602f038e04e25311adb17ea8f2a86421e874ec

When you choose to generate C++ code, the C++ compiler will be used
automatically instead of C compiler. So in your case just replace arm tools with x86 tools in ert_qnx.tmf and qnxtools.mak (which you already did, but you also made other changes, which need to be undone), set qnx_simple model to generate C++ code and you should be good to go.

Let me know how it works for you.

**Comment by wiescho** [comment]
Hi,

thank you for the changes. But now the I got the following linking error:

```
C:/QNX650/host/win32/x86/usr/bin/qcc -V4.4.2,gcc_ntox86_cpp -Bstatic -static -lc -lm -lcpp -lstdc++  -o ../qnx_simple  ert_qnx_utils.o rtiostream_utils.o qnx_simple_data.o qnx_simple.o ert_main.o ext_qnx_work.o ext_qnx_svr.o updown_qnx.o rtiostream_tcpip_qnx.o rtiostream_interface_qnx.o @qnx_simple_ref.rsp     -lm -lsocket -lc
ert_qnx_utils.o:(.eh_frame+0x12): undefined reference to `__gxx_personality_v0' 
rtiostream_utils.o:(.eh_frame+0x12): undefined reference to `__gxx_personality_v0' 
qnx_simple.o:(.eh_frame+0x12): undefined reference to `__gxx_personality_v0' 
ert_main.o:(.eh_frame+0x12): undefined reference to `__gxx_personality_v0' 
ext_qnx_work.o:(.eh_frame+0x12): undefined reference to `__gxx_personality_v0' 
ext_qnx_svr.o:(.eh_frame+0x12): more undefined references to `__gxx_personality_v0' follow 
cc: C:/QNX650/host/win32/x86/usr/bin/ntox86-ld caught signal 1
```

I added the option `-lstdc++` so it should link the standard cpp library but the error still remains.

also as suggested at http://stackoverflow.com/questions/329059/what-is-gxx-personality-v0-for
I added the line `-fno-exceptions` in the options and now it will link your simple demo but when using code witch requires exceptions, it produces the same error. 

Thank you for all your work

**Comment by kyak** [comment]
Well, the problem with __gxx_personality_v0 error was known and it was the reason why -lstdc++ was added to the flags. You shouldn't have to add it, because it's already there - so double check your changes are coherent.

It might be that your S-function requires specific other flags to compile or linke, so feel free to add those yourself. If you believe that your flags qualify as generic and won't break other users's setup, feel free to create a pull request.
